CREATE DATABASE BT_FAST
GO

USE BT_FAST
CREATE TABLE Tinh_TP
(
	Ma_T_TP VARCHAR(3) PRIMARY KEY,
	DT  NUMERIC(18,3),
	DS NUMERIC(18,3),
	Ten_T_TP NVARCHAR(30)
)

CREATE TABLE MIEN
(
	Ma_T_TP VARCHAR(3) NOT NULL,
	Mien NVARCHAR(30)
)
CREATE TABLE Biengioi 
(
	Nuoc NVARCHAR(30),
	Ma_T_TP VARCHAR(3) NOT NULL
)
CREATE TABLE Langgieng
(
	Ma_T_TP VARCHAR(3) NOT NULL,
	LG NVARCHAR(30)
)
ALTER TABLE Mien ADD CONSTRAINT FK_mientinh FOREIGN KEY(Ma_T_TP) REFERENCES Tinh_TP(Ma_T_TP)
ALTER TABLE Langgieng ADD CONSTRAINT FK_LG_Tinh FOREIGN KEY(Ma_T_TP) REFERENCES Tinh_TP(Ma_T_TP)
ALTER TABLE Biengioi ADD CONSTRAINT FK_Bg_Tinh FOREIGN KEY(Ma_T_TP) REFERENCES Tinh_TP(Ma_T_TP)


-- 1 Xuất ra tên tỉnh , thành phố biên giới thuộc miền iinput
DECLARE @_Tenmien NVARCHAR(30)
SET @_tenmien = N'Trung'
SELECT T.Ten_T_TP
FROM TINH_TP AS T INNER JOIN 
WHERE 